version: "3.8"

services:
  app:
    build: ./app
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - API_SERVER_HOST=${API_SERVER_HOST}
      - API_CLIENT_HOST=${API_CLIENT_HOST}
      - NEXT_WEBPACK_USEPOLLING=1
      - NODE_ENV=development
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/api
      - /api/node_modules
    environment:
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS}
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  db:
    driver: local